### PR TITLE
Improve responsiveness of platform

### LINKED ISSUE #34: Responsiveness of the platform - Pt. 1
There are some smaller issues with the responsiveness of the platform:

- Footer has no padding towards the bottom (on smaller screens)
- Manage my account has some margin issues
- Hashes of samples (sha256) aren't wrapped, so they overflow.
- Same happens to username/password of FTP upload section

### PR DESCRIPTION
**Pull request by madan96**
- [x] Wrap hashes of samples
- [x] Wrap username/password of FTP upload section
- [x] Resolve margin issues of manage account
- [x] Add padding to footer at bottom 

Fixes #34

### CODE REVIEW

**Comment by canihavesomecoffee** [comment]
Hi, most fixes look good, but I'd prefer overriding the css in the app.css file, so that we can seamlessly upgrade to newer Foundation versions afterwards.

You can either open a new PR with those changes, or revert these ones and update the file.

**Comment by madan96** [comment]
Thanks, making changes in the app.css would definitely be a better option. 
So basically, I have to copy the changes made into foundation files into the app.css file. Is that correct?

**Comment by canihavesomecoffee** [comment]
Yes, just take over the modified specifiers with the changes and put those in app.css :)

**Comment by madan96** [comment]
@canihavesomecoffee Can you please review the changes?

**Pull request merged**
