### PR TITLE
Accounted for non-zero exit_code

### PR DESCRIPTION
**Pull request by ManveerBasra**
Didn't look like the models needed to be changed.

### CODE REVIEW

**Comment by canihavesomecoffee** [comment]
Your current PR doesn't cover cases like:
- Expected exit code 0, got 10
- Expected exit code 10, got 0
- ...

**Comment by ManveerBasra** [comment]
Is this an improvement? I'm having a hard time understanding how the functions are called and where the return values actually go.

**Comment by canihavesomecoffee** [comment]
No improvement sadly.

If you need help, ask me on Slack, I'll give you some pointers :)

**Comment by ManveerBasra** [comment]
Explanation on Slack, hopefully I did something correct this time :upside_down_face:

**Comment by ManveerBasra** [comment]
Fixes #12

**Pull request merged**
